config/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'portfolio'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('users/', include('users.urls')),
]

portfolio/urls.py
from django.urls import path
from . import views

app_name = "portfolio"

urlpatterns = [
    path('', views.home_page_view, name='home'),
    path('aboutme/', views.aboutme_page_view, name='aboutme'),
    path('projects/', views.projects_page_view, name='projects'),
    path('projects/add_project/', views.add_project_view, name='add_project'),
    path('blog/remove_project/<int:project_id>', views.remove_project_view, name='remove_project'),
    path('graduation/', views.graduation_page_view, name='graduation'),
    path('graduation/add_subject/', views.add_subject_view, name='add_subject'),
    path('blog/remove_subject/<int:subject_id>', views.remove_subject_view, name='remove_subject'),
    path('blog/', views.blog_page_view, name='blog'),
    path('blog/add_post/', views.add_post_view, name='add_post'),
    path('blog/remove_post/<int:post_id>', views.remove_post_view, name='remove_post'),
    path('webdev/', views.webdev_page_view, name='webdev'),
]

project_pictures/config/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
]

portfolio/models.py
from django.db import models


# Create your models here.
class Teacher(models.Model):
    name = models.CharField(max_length=50)
    lusofona = models.CharField(max_length=500)
    linkedin = models.CharField(max_length=500)

    def __str__(self):
        return f"{self.name}"


class Subject(models.Model):
    name = models.CharField(max_length=50)
    year = models.IntegerField()
    semester = models.IntegerField()
    ects = models.IntegerField()
    lusofona = models.CharField(max_length=500)
    ranking = models.CharField(max_length=5)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name}"


class Project(models.Model):
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=500)
    image = models.CharField(max_length=500)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    year = models.IntegerField()

    def __str__(self):
        return f"{self.title}"


class Post(models.Model):
    id = models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")
    author = models.CharField(max_length=50)
    title = models.CharField(max_length=50)
    date = models.DateTimeField(auto_now_add=True)
    description = models.CharField(max_length=500)
    image = models.CharField(max_length=500, default="")
    link = models.CharField(max_length=500, default="")

    def __str__(self):
        return f"{self.title}"

portfolio/forms.py
from django import forms
from django.forms import ModelForm
from .models import Teacher, Subject, Project, Post


class SubjectForm(ModelForm):
    class Meta:
        model = Subject
        fields = ("name", "year", "semester", "ects", "lusofona", "ranking", "teacher")

        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control", "placeholder": "Nome", "max": 50}),
            "year": forms.NumberInput(attrs={"class": "form-control"}),
            "semester": forms.NumberInput(attrs={"class": "form-control"}),
            "ects": forms.NumberInput(attrs={"class": "form-control"}),
            "lusofona": forms.TextInput(attrs={"class": "form-control", "placeholder": "Link da Lusófuna", "max": 500}),
            "ranking": forms.TextInput(attrs={"class": "form-control", "placeholder": "Ranking", "max": 5}),
            "teacher": forms.Select(attrs={"class": "form-control"}),
        }

        labels = {
            "name": "Nome",
            "year": "Ano",
            "semester": "Semestre",
            "ects": "ECTs",
            "lusofona": "Link da Lusófuna",
            "ranking": "Ranking",
        }

        help_texts = {
            "name": "",
            "year": "",
            "semester": "",
            "ects": "",
            "lusofona": "",
            "ranking": "",
        }


class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ("title", "description", "image", "subject", "year")

        widgets = {
            "title": forms.TextInput(attrs={"class": "form-control", "placeholder": "Autor", "max": 50}),
            "description": forms.TextInput(attrs={"class": "form-control", "placeholder": "Descrição", "max": 500}),
            "image": forms.TextInput(attrs={"class": "form-control", "placeholder": "Imagem", "max": 500}),
            "subject": forms.Select(attrs={"class": "form-control"}),
            "year": forms.NumberInput(attrs={"class": "form-control"}),
        }

        labels = {
            "title": "Autor",
            "description": "Descrição",
            "image": "Imagem",
            "year": "Ano",
        }

        help_texts = {
            "title": "",
            "description": "",
            "image": "",
            "year": "",
        }


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ("author", "title", "description", "link", "image")

        widgets = {
            "author": forms.TextInput(attrs={"class": "form-control", "placeholder": "Autor", "max": 50}),
            "title": forms.TextInput(attrs={"class": "form-control", "placeholder": "Título", "max": 50}),
            "description": forms.TextInput(attrs={"class": "form-control", "placeholder": "Descrição", "max": 500}),
            "link": forms.TextInput(attrs={"class": "form-control", "placeholder": "Link", "max": 500}),
            "image": forms.TextInput(attrs={"class": "form-control", "placeholder": "Imagem", "max": 500}),
        }

        labels = {
            "author": "Autor",
            "title": "Título",
            "description": "Descrição",
            "link": "Link",
            "image": "Imagem",
        }

        help_texts = {
            "author": "",
            "title": "",
            "description": "",
            "link": "",
            "image": "",
        }

portfolio/views.py
import datetime

from django.shortcuts import render, redirect
from portfolio.forms import SubjectForm, ProjectForm, PostForm
from portfolio.models import Subject, Project, Post


def home_page_view(request):
    return render(request, 'portfolio/home.html')


def aboutme_page_view(request):
    return render(request, 'portfolio/aboutme.html')


def projects_page_view(request):
    context = {'projects': Project.objects.all()}
    return render(request, 'portfolio/projects.html', context)


def graduation_page_view(request):
    context = {'subjects': Subject.objects.all()}
    return render(request, 'portfolio/graduation.html', context)


def blog_page_view(request):
    context = {'posts': Post.objects.all()}
    return render(request, 'portfolio/blog.html', context)


def add_subject_view(request):
    form = SubjectForm(request.POST)
    if form.is_valid():
        form.save()
        return redirect("portfolio:home")
    context = {'form': form}
    return render(request, 'portfolio/add_subject.html', context)


def remove_subject_view(request, subject_id):
    Subject.objects.get(id=subject_id).delete()
    return redirect("portfolio:graduation")


def add_project_view(request):
    form = ProjectForm(request.POST)
    if form.is_valid():
        form.save()
        return redirect("portfolio:home")
    context = {'form': form}
    return render(request, 'portfolio/add_project.html', context)


def remove_project_view(request, project_id):
    Project.objects.get(id=project_id).delete()
    return redirect("portfolio:projects")


def add_post_view(request):
    form = PostForm(request.POST)
    if form.is_valid():
        form.save()
        return redirect("portfolio:blog")
    context = {'form': form}
    return render(request, 'portfolio/add_post.html', context)


def remove_post_view(request, post_id):
    Post.objects.get(id=post_id).delete()
    return redirect("portfolio:blog")


def webdev_page_view(request):
    return render(request, 'portfolio/webdev.html')


def index(request):
    pass

portfolio/templates/portfolio/aboutme.html
 <!-- aboutme.html -->

    {% extends 'portfolio/layout.html' %}

    {% block main %}
    <div class="spacer"></div>
    <div class="licenciatura">
        <div class="text">
            <h1>Licenciatura</h1>
            <p>Neste momento, estou a realizar uma <a href="{% url 'portfolio:graduation' %}">Licenciatura de Engenharia Informática</a> na Universidade Lusófona de Humanidades e Tecnologias.</p>
        </div>
        <div class="photo">
            {% load static %}
            <a href="https://www.ulusofona.pt/"><img src="{% static 'portfolio/images/logo_ulht_horizontal.png' %}"></a>
        </div>
    </div>
    <div class="educacao">
        <div class="text">
            <h1>Educação</h1>
            <p>Realizei os primeiros quatro anos de escolaridade (1º ao 4º ano) na Escola Básica 1 nº 4 de Alverca.</p>
            <p>Realizei os cinco seguintes anos de escolaridade (5º ao 9º ano) na Escola Básica 2,3 Pedro Jacques de Magalhães, em Alverca.</p>
            <p>Por fim, realizei o curso de Ciências e Tecnologias na Escola Secundária Gago Coutinho, em Alverca.</p>
        </div>
    </div>
    <div class="competencias">
        <div class="text">
            <h1>Competências</h1>
            <p>Em termos práticos, tenho conhecimentos em diversas Linguagens: C, Lua, Kotlin, Java, entre outras.</p>
        </div>
    </div>
    <div class="interesses">
        <div class="text">
            <h1>Interesses</h1>
            <p>Desde pequeno que demonstrei grande interesse por videojogos e, por consequência, por computadores.</p>
            <p>Esse gosto criou o interesse pela área de desenvolvimento de jogos, tendo já realizado scripts básicos para</p>
            <p>FiveM e realizado modelação 3D de forma a modificar o mapa do jogo.</p>
        </div>
    </div>
    <div class="spacer"></div>
    {% endblock %}

portfolio/templates/portfolio/add_post.html
 <!-- blog.html -->

    {% extends 'portfolio/layout.html' %}

    {% block main %}
    <h3>Nova publicação</h3>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <a href="{% url 'portfolio:blog' %}" class="btn btn-warning">Cancelar</a>
        <input type="submit" value="Gravar" class="btn btn-success" >
    </form>
    {% endblock %}

portfolio/templates/portfolio/add_project.html
    <!-- add_project.html -->

    {% extends 'portfolio/layout.html' %}

    {% block main %}
    <h3>Novo projeto</h3>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <a href="{% url 'portfolio:projects' %}" class="btn btn-warning">Cancelar</a>
        <input type="submit" value="Gravar" class="btn btn-success" >
    </form>
    {% endblock %}

portfolio/templates/portfolio/add_subject.html
    <!-- add_subject.html -->

    {% extends 'portfolio/layout.html' %}

    {% block main %}
    <h3>Nova cadeira</h3>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <a href="{% url 'portfolio:graduation' %}" class="btn btn-warning">Cancelar</a>
        <input type="submit" value="Gravar" class="btn btn-success" >
    </form>
    {% endblock %}

portfolio/templates/portfolio/blog.html
 <!-- blog.html -->

    {% extends 'portfolio/layout.html' %}

    {% block main %}
    <div class="posts">
        <a href="{% url 'portfolio:add_post' %}" class="">Criar publicação</a>
        {% for post in posts %}
        <div class="post">
            <h2 class="title">{{ post.title }}</h2>
            <p class="description">{{ post.description }}</p>
            <img src="{{ post.image }}" class="image">
            <p class="link">{{ post.link }}</p>
            <h6 class="author">Postado por: {{ post.author }} no dia {{post.date.day}}/{{post.date.month}}/{{post.date.year}} às {{post.date.hour}}:{{post.date.minute}}</h6>
            {% if request.user.is_staff %}
                <a href="{% url 'portfolio:remove_post' post.id %}">Apagar publicação</a>
            {% endif %}
        </div>
        {% endfor %}
    </div>
    {% endblock %}

portfolio/templates/portfolio/graduation.html
 <!-- graduation.html -->

    {% extends 'portfolio/layout.html' %}

    {% block main %}
    <div class="graduation">
        <div>
            {% if request.user.is_staff %}
                <a href="{% url 'portfolio:add_subject' %}" class="">Adicionar cadeira</a>
            {% endif %}
        </div>
        <div>
            {% for subject in subjects %}
            <div class="subject">
                <a href="{{ subject.lusofona }}"><h2 class="name">{{ subject.name }}</h2></a>
                <p class="year">{{ subject.year }}º ano</p>
                <p class="semester">{{ subject.semester }}º semestre</p>
                <p class="ects">{{ subject.ects }} ECTs</p>
                <p class="ranking">{{ subject.ranking }}</p>
                <div class="teacher">
                    <h3 class="name">Docente: {{ subject.teacher.name }}</h3>
                    <div>
                        {% load static %}
                        <a href="{{ subject.teacher.lusofona }}"><img src="{% static 'portfolio/images/logo_ulht.png' %}" class="lusofona"></a>
                        <a href="{{ subject.teacher.linkedin }}"><img src="{% static 'portfolio/images/logo_linkedin.png' %}" class="linkedin"></a>
                    </div>
                </div>
                {% if request.user.is_staff %}
                    <a href="{% url 'portfolio:remove_subject' subject.id %}">Apagar cadeira</a>
                {% endif %}
            </div>
            {% endfor %}
         </div>
    </div>
    {% endblock %}

portfolio/templates/portfolio/home.html
 <!-- home.html -->

    {% extends 'portfolio/layout.html' %}

    {% block main %}
    <div class="spacer"></div>
    <div class="home">
        <div class="photo">
            {% load static %}
            <a href="{% url 'portfolio:aboutme' %}"><img src="{% static 'portfolio/images/me.png' %}"></a>
        </div>
        <div class="text">
            <h1>Alexandre Godinho</h1>
            <p>Bem-vindo! Esta página dedica-se a apresentar o meu percurso escolar, académico e pessoal.</p>
            <p>Este precurso encontra-se exposto por categorias de forma a facilitar a sua vizualização.</p>
            <p>Para informações mais detalhadas pressione <a href="{% url 'portfolio:aboutme' %}">SOBRE MIM</a>!</p>
        </div>
        <div class="social">
            <a href="https://www.facebook.com/alexandre.godinho.395"><img src="{% static 'portfolio/images/black_facebook.png' %}"></a>
            <a href="https://www.instagram.com/god_alexandre/"><img src="{% static 'portfolio/images/black_instagram.png' %}"></a>
            <a href="https://www.linkedin.com/in/alexandre-godinho-221840182/"><img src="{% static 'portfolio/images/black_linkedin.png' %}"></a>
            <a href="https://moodle.ensinolusofona.pt/user/profile.php?id=5967"><img src="{% static 'portfolio/images/black_ulht.png' %}"></a>
        </div>
    </div>
    <div class="spacer"></div>
    {% endblock %}

portfolio/templates/portfolio/layout.html
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <title>Alexandre Godinho</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'portfolio/css/estilos.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@500&display=swap" rel="stylesheet">
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            currentTime();

            // Envia pedido GET ao URL da API Exchange
            fetch('https://api.ipma.pt/open-data/forecast/meteorology/cities/daily/hp-daily-forecast-day0.json')

                // Põe resposta no formato json
                .then(response => response.json())

                .then(data => {

                    // Obter o valor dos dados
                    const valor = data;
                    console.log(valor)
                    const valorMin = data.data[12].tMin;
                    const valorMax = data.data[12].tMax;

                    // Verifica se o valor é válido.
                    if (valorMin !== undefined && valorMax !== undefined) {
                        // Mostra valor de cambio no ecrã
                        document.querySelector('#temp').innerHTML =
                            `Temperatura em Lisboa: ${valorMin}º - ${valorMax}º`;
                    } else {
                        // Display error on the screen
                        document.querySelector('#temp').innerHTML = 'Sem temperatura.';
                    }
                })
                // Catch apanha erros e mostra na consola
                .catch(error => {
                    console.log('Error:', error);
                });

            // Previne submissão do formulário
            return false
        });

        function currentTime() {
          let date = new Date();
          let hh = date.getHours();
          let mm = date.getMinutes();
          let ss = date.getSeconds();
          let day = date.getDate();
          let month = date.getMonth() + 1;
          let year = date.getFullYear();

           hh = (hh < 10) ? "0" + hh : hh;
           mm = (mm < 10) ? "0" + mm : mm;
           ss = (ss < 10) ? "0" + ss : ss;

           let time = day + "/" + month + "/" + year + " " + hh + ":" + mm + ":" + ss;

          document.getElementById("clock").innerText = time;
          let t = setTimeout(function(){ currentTime() }, 1000);
        }

        currentTime();
    </script>
</head>
<body>
    <header>
        <a href="{% url 'portfolio:home' %}">Alexandre Godinho</a>
        <nav class="navbar">
            <a href="{% url 'portfolio:home' %}">HOME</a>
            <a href="{% url 'portfolio:aboutme' %}">SOBRE MIM</a>
            <a href="{% url 'portfolio:projects' %}">PROJETOS</a>
            <a href="{% url 'portfolio:blog' %}">BLOG</a>
            <a href="{% url 'portfolio:webdev' %}">PROGRAMAÇÃO WEB</a>
            {% if request.user.is_authenticated %}
                <a href="{% url 'users:logout' %}" class="">LOGOUT</a>
            {% else %}
                <a href="{% url 'users:login' %}" class="">LOGIN</a>
            {% endif %}
        </nav>
    </header>
	<main>
        {% block main %}
	    {% endblock main %}
    </main>
    <footer>
        <div id="temp"></div>
        <div>ULHT 2022</div>
        <div id="clock" onload="currentTime()"></div>
    </footer>
</body>
</html>

portfolio/templates/portfolio/projects.html
 <!-- projects.html -->

    {% extends 'portfolio/layout.html' %}

    {% block main %}
    <div class="projects">
        {% if request.user.is_staff %}
            <a href="{% url 'portfolio:add_project' %}" class="">Adicionar projeto</a>
        {% endif %}
        {% for project in projects %}
        <div class="project">
            <h2 class="title">{{ project.title }}</h2>
            <div class="projectcontent">
                <div class="projecttext">
                    <p class="subject">Realizado no âmbito de <a href="{{ project.subject.lusofona }}">{{ project.subject.name }}</a> em {{ project.year }}</p>
                    <p class="description">{{ project.description }}</p>
                </div>
                <img src="{{ project.image }}" class="image">
            </div>
            {% if request.user.is_staff %}
                <a href="{% url 'portfolio:remove_project' project.id %}">Apagar projeto</a>
            {% endif %}
        </div>
        {% endfor %}
    </div>
    {% endblock %}

portfolio/templates/portfolio/webdev.html
 <!-- webdev.html -->

    {% extends 'portfolio/layout.html' %}

    {% block main %}
    <div class="spacer"></div>
    <div class="pwlabs">
        <div class="text">
            <h1>Porogramação Web</h1>
            <p>De modo a consultar os laboratórios anteriores carregue <a href="https://a21804766-pw-lab1.herokuapp.com/">AQUI</a>.</p>
        </div>
    </div>
    <div class="video">
        <div class="text">
            <h1>Sobre a página</h1>
            <p>Ao longo desta página foi utilizado HTML, CSS, Python, Django e JavaScript.</p>
            <iframe width="560" height="315" src="https://www.youtube.com/embed/2QYkmUKv_Q4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
    </div>
    <div class="spacer"></div>
    {% endblock %}